# -*- coding: utf-8 -*-
"""Stock Market Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JCZArnQfswZDMOHHHP0DhV-ekih51N40
"""

# Commented out IPython magic to ensure Python compatibility.
"""
🚀 ENHANCED STOCK MARKET DATA PIPELINE v3.0 - GOOGLE COLAB EDITION
====================================================================
✨ COMPLETE & READY TO RUN WITH VERIFICATION
⏱️  ~15-20 minutes runtime
🔄 100% rerunnable
📊 26 stocks × 10 years
✅ Complete data verification included
"""

# ============================================
# INSTALLATION & IMPORTS
# ============================================

import subprocess
import sys

def install_packages():
    """Install required packages"""
    packages = ['yfinance', 'psycopg2-binary', 'scipy', 'requests', 'Pillow', 'tqdm']
    for package in packages:
        try:
            __import__(package.replace('-', '_').split('[')[0])
        except ImportError:
            print(f"📦 Installing {package}...")
            subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", package])

install_packages()

import yfinance as yf
import pandas as pd
import numpy as np
import psycopg2
from psycopg2.extras import execute_batch
from datetime import datetime, timedelta
import time
import warnings
from tqdm import tqdm
import requests
from PIL import Image
from io import BytesIO
import base64
from scipy.signal import argrelextrema
import logging
import os

warnings.filterwarnings('ignore')

# ============================================
# CONFIGURATION
# ============================================

class Config:
    """Centralized configuration - NEON DATABASE CONFIGURED"""

    # ✅ NEON DATABASE - CONFIGURED AND READY
    DB_CONFIG = {
        'host': os.getenv('DB_HOST', 'ep-dark-math-a4bf2qbn-pooler.us-east-1.aws.neon.tech'),
        'database': os.getenv('DB_NAME', 'neondb'),
        'user': os.getenv('DB_USER', 'neondb_owner'),
        'password': os.getenv('DB_PASSWORD', 'npg_HeNucnZs0OR2'),
        'port': int(os.getenv('DB_PORT', '5432')),
        'sslmode': 'require'
    }

    STOCK_PORTFOLIO = {
        'Technology': ['AAPL', 'MSFT', 'GOOGL', 'NVDA', 'META', 'AMD', 'INTC', 'ORCL'],
        'E-commerce & Retail': ['AMZN', 'SHOP', 'WMT'],
        'Automotive & Energy': ['TSLA', 'F', 'GM', 'XOM'],
        'Entertainment': ['NFLX', 'DIS', 'SPOT'],
        'Financial': ['V', 'MA', 'JPM'],
        'Healthcare': ['JNJ', 'PFE', 'MRNA'],
        'Consumer': ['KO', 'PEP']
    }

    COMPANY_NAMES = {
        'AAPL': 'Apple Inc.', 'MSFT': 'Microsoft Corporation', 'GOOGL': 'Alphabet Inc.',
        'NVDA': 'NVIDIA Corporation', 'META': 'Meta Platforms Inc.',
        'AMD': 'Advanced Micro Devices', 'INTC': 'Intel Corporation',
        'ORCL': 'Oracle Corporation', 'AMZN': 'Amazon.com Inc.', 'SHOP': 'Shopify Inc.',
        'WMT': 'Walmart Inc.', 'TSLA': 'Tesla Inc.', 'F': 'Ford Motor Company',
        'GM': 'General Motors', 'XOM': 'Exxon Mobil Corporation',
        'NFLX': 'Netflix Inc.', 'DIS': 'The Walt Disney Company',
        'SPOT': 'Spotify Technology', 'V': 'Visa Inc.',
        'MA': 'Mastercard Inc.', 'JPM': 'JPMorgan Chase & Co.',
        'JNJ': 'Johnson & Johnson', 'PFE': 'Pfizer Inc.', 'MRNA': 'Moderna Inc.',
        'KO': 'The Coca-Cola Company', 'PEP': 'PepsiCo Inc.'
    }

    COMPANY_DOMAINS = {
        'AAPL': 'apple.com', 'MSFT': 'microsoft.com', 'GOOGL': 'google.com',
        'NVDA': 'nvidia.com', 'META': 'meta.com', 'AMD': 'amd.com',
        'INTC': 'intel.com', 'ORCL': 'oracle.com', 'AMZN': 'amazon.com',
        'SHOP': 'shopify.com', 'WMT': 'walmart.com', 'TSLA': 'tesla.com',
        'F': 'ford.com', 'GM': 'gm.com', 'XOM': 'exxonmobil.com',
        'NFLX': 'netflix.com', 'DIS': 'disney.com', 'SPOT': 'spotify.com',
        'V': 'visa.com', 'MA': 'mastercard.com', 'JPM': 'jpmorganchase.com',
        'JNJ': 'jnj.com', 'PFE': 'pfizer.com', 'MRNA': 'modernatx.com',
        'KO': 'coca-cola.com', 'PEP': 'pepsi.com'
    }

    BATCH_SIZE = 1000
    MAX_RETRIES = 3
    RETRY_DELAY = 2
    HISTORY_PERIOD = "10y"

    @classmethod
    def get_all_stocks(cls):
        return [stock for stocks in cls.STOCK_PORTFOLIO.values() for stock in stocks]

    @classmethod
    def validate_db_config(cls):
        required_keys = ['host', 'database', 'user', 'password', 'port']
        for key in required_keys:
            if cls.DB_CONFIG.get(key) in [None, '', 'YOUR_CLOUD_HOST', 'YOUR_PASSWORD']:
                return False
        return True

# ============================================
# LOGGING
# ============================================

def setup_logging():
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s | %(levelname)s | %(message)s',
        datefmt='%H:%M:%S'
    )
    return logging.getLogger(__name__)

logger = setup_logging()

# ============================================
# DATABASE
# ============================================

class DatabaseManager:
    def __init__(self, config):
        self.config = config
        self.conn = None

    def connect(self):
        try:
            self.conn = psycopg2.connect(**self.config)
            logger.info("✅ Database connected successfully")
            return True
        except Exception as e:
            logger.error(f"❌ Database connection failed: {e}")
            return False

    def disconnect(self):
        if self.conn:
            self.conn.close()
            logger.info("🔌 Database disconnected")

    def execute_query(self, query, params=None):
        try:
            cursor = self.conn.cursor()
            cursor.execute(query, params)
            self.conn.commit()
            cursor.close()
            return True
        except Exception as e:
            logger.error(f"Query execution error: {e}")
            self.conn.rollback()
            return False

    def fetch_query(self, query, params=None):
        """Fetch query results"""
        try:
            cursor = self.conn.cursor()
            cursor.execute(query, params)
            results = cursor.fetchall()
            cursor.close()
            return results
        except Exception as e:
            logger.error(f"Fetch query error: {e}")
            return []

    def batch_insert(self, query, data, page_size=1000):
        if not data:
            return 0
        try:
            cursor = self.conn.cursor()
            execute_batch(cursor, query, data, page_size=page_size)
            self.conn.commit()
            cursor.close()
            return len(data)
        except Exception as e:
            logger.error(f"Batch insert error: {e}")
            self.conn.rollback()
            return 0

    def verify_table_data(self, table_name):
        """Verify data in a specific table"""
        query = f"SELECT COUNT(*) FROM {table_name}"
        try:
            cursor = self.conn.cursor()
            cursor.execute(query)
            count = cursor.fetchone()[0]
            cursor.close()
            return count
        except Exception as e:
            logger.error(f"Verification error for {table_name}: {e}")
            return 0

# ============================================
# CREATE SCHEMA
# ============================================

def create_database_schema(db):
    logger.info("📋 Creating database schema...")

    queries = [
        # Stocks dimension
        """CREATE TABLE IF NOT EXISTS dim_stocks (
            stock_id SERIAL PRIMARY KEY,
            symbol VARCHAR(10) UNIQUE NOT NULL,
            company_name VARCHAR(200),
            display_name VARCHAR(200),
            logo_base64 TEXT,
            logo_file_path VARCHAR(500),
            sector VARCHAR(100),
            industry VARCHAR(100),
            website VARCHAR(200),
            description TEXT,
            country VARCHAR(50),
            currency VARCHAR(10),
            exchange VARCHAR(50),
            employees BIGINT,
            market_cap BIGINT,
            updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )""",

        "CREATE INDEX IF NOT EXISTS idx_stocks_symbol ON dim_stocks(symbol)",
        "CREATE INDEX IF NOT EXISTS idx_stocks_sector ON dim_stocks(sector)",

        # Real-time quotes
        """CREATE TABLE IF NOT EXISTS fact_realtime_quotes (
            quote_id SERIAL PRIMARY KEY,
            symbol VARCHAR(10),
            fetch_timestamp TIMESTAMP NOT NULL,
            trading_date DATE NOT NULL,
            current_price DECIMAL(12, 4),
            price_change DECIMAL(12, 4),
            change_percent DECIMAL(8, 4),
            volume BIGINT,
            open DECIMAL(12, 4),
            high DECIMAL(12, 4),
            low DECIMAL(12, 4),
            previous_close DECIMAL(12, 4),
            market_cap BIGINT,
            avg_volume BIGINT,
            day_range VARCHAR(50)
        )""",

        "CREATE INDEX IF NOT EXISTS idx_quotes_symbol_date ON fact_realtime_quotes(symbol, trading_date DESC)",

        # Daily prices with technical indicators
        """CREATE TABLE IF NOT EXISTS fact_daily_prices (
            price_id SERIAL PRIMARY KEY,
            symbol VARCHAR(10),
            trading_date DATE NOT NULL,
            open DECIMAL(12, 4),
            high DECIMAL(12, 4),
            low DECIMAL(12, 4),
            close DECIMAL(12, 4),
            adjusted_close DECIMAL(12, 4),
            volume BIGINT,
            dividends DECIMAL(10, 4),
            stock_splits DECIMAL(10, 4),
            ma_20 DECIMAL(12, 4),
            ma_50 DECIMAL(12, 4),
            ma_200 DECIMAL(12, 4),
            ema_12 DECIMAL(12, 4),
            ema_26 DECIMAL(12, 4),
            rsi_14 DECIMAL(8, 2),
            macd DECIMAL(12, 6),
            macd_signal DECIMAL(12, 6),
            macd_histogram DECIMAL(12, 6),
            bollinger_upper DECIMAL(12, 4),
            bollinger_middle DECIMAL(12, 4),
            bollinger_lower DECIMAL(12, 4),
            bollinger_width DECIMAL(12, 4),
            stochastic_k DECIMAL(8, 2),
            stochastic_d DECIMAL(8, 2),
            atr_14 DECIMAL(12, 4),
            obv BIGINT,
            vwap DECIMAL(12, 4),
            volatility_30 DECIMAL(8, 4),
            daily_return DECIMAL(8, 4),
            avg_volume_20 BIGINT,
            volume_ratio DECIMAL(8, 4),
            momentum_10 DECIMAL(8, 4),
            momentum_20 DECIMAL(8, 4),
            UNIQUE(symbol, trading_date)
        )""",

        "CREATE INDEX IF NOT EXISTS idx_daily_symbol_date ON fact_daily_prices(symbol, trading_date DESC)",

        # Fundamentals
        """CREATE TABLE IF NOT EXISTS fact_fundamentals (
            fundamental_id SERIAL PRIMARY KEY,
            symbol VARCHAR(10),
            updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            market_cap BIGINT,
            enterprise_value BIGINT,
            trailing_pe DECIMAL(10, 2),
            forward_pe DECIMAL(10, 2),
            peg_ratio DECIMAL(10, 2),
            price_to_book DECIMAL(10, 2),
            price_to_sales DECIMAL(10, 2),
            enterprise_to_revenue DECIMAL(10, 2),
            enterprise_to_ebitda DECIMAL(10, 2),
            profit_margin DECIMAL(8, 4),
            operating_margin DECIMAL(8, 4),
            return_on_assets DECIMAL(8, 4),
            return_on_equity DECIMAL(8, 4),
            revenue BIGINT,
            revenue_per_share DECIMAL(10, 2),
            gross_profit BIGINT,
            ebitda BIGINT,
            net_income BIGINT,
            eps DECIMAL(10, 2),
            book_value DECIMAL(10, 2),
            dividend_rate DECIMAL(10, 2),
            dividend_yield DECIMAL(8, 4),
            payout_ratio DECIMAL(8, 4),
            beta DECIMAL(8, 4),
            week_52_high DECIMAL(12, 4),
            week_52_low DECIMAL(12, 4),
            fifty_day_avg DECIMAL(12, 4),
            two_hundred_day_avg DECIMAL(12, 4),
            shares_outstanding BIGINT,
            float_shares BIGINT,
            shares_short BIGINT,
            short_ratio DECIMAL(8, 2),
            held_percent_institutions DECIMAL(8, 4),
            held_percent_insiders DECIMAL(8, 4)
        )""",

        "CREATE INDEX IF NOT EXISTS idx_fundamentals_symbol ON fact_fundamentals(symbol)",

        # Income statement
        """CREATE TABLE IF NOT EXISTS fact_income_statement (
            income_id SERIAL PRIMARY KEY,
            symbol VARCHAR(10),
            fiscal_date DATE,
            period VARCHAR(20),
            total_revenue BIGINT,
            cost_of_revenue BIGINT,
            gross_profit BIGINT,
            research_development BIGINT,
            selling_general_admin BIGINT,
            operating_expenses BIGINT,
            operating_income BIGINT,
            interest_expense BIGINT,
            other_income_expense BIGINT,
            income_before_tax BIGINT,
            income_tax_expense BIGINT,
            net_income BIGINT,
            ebitda BIGINT,
            basic_eps DECIMAL(10, 4),
            diluted_eps DECIMAL(10, 4),
            gross_margin DECIMAL(8, 4),
            operating_margin DECIMAL(8, 4),
            net_margin DECIMAL(8, 4),
            ebitda_margin DECIMAL(8, 4),
            UNIQUE(symbol, fiscal_date, period)
        )""",

        "CREATE INDEX IF NOT EXISTS idx_income_symbol_date ON fact_income_statement(symbol, fiscal_date DESC)",

        # Balance sheet
        """CREATE TABLE IF NOT EXISTS fact_balance_sheet (
            balance_id SERIAL PRIMARY KEY,
            symbol VARCHAR(10),
            fiscal_date DATE,
            period VARCHAR(20),
            total_assets BIGINT,
            current_assets BIGINT,
            cash_and_equivalents BIGINT,
            accounts_receivable BIGINT,
            inventory BIGINT,
            property_plant_equipment BIGINT,
            goodwill BIGINT,
            total_liabilities BIGINT,
            current_liabilities BIGINT,
            accounts_payable BIGINT,
            short_term_debt BIGINT,
            long_term_debt BIGINT,
            total_equity BIGINT,
            retained_earnings BIGINT,
            working_capital BIGINT,
            total_debt BIGINT,
            net_debt BIGINT,
            current_ratio DECIMAL(8, 4),
            debt_to_equity DECIMAL(10, 4),
            debt_to_assets DECIMAL(8, 4),
            UNIQUE(symbol, fiscal_date, period)
        )""",

        "CREATE INDEX IF NOT EXISTS idx_balance_symbol_date ON fact_balance_sheet(symbol, fiscal_date DESC)",

        # Cash flow
        """CREATE TABLE IF NOT EXISTS fact_cash_flow (
            cashflow_id SERIAL PRIMARY KEY,
            symbol VARCHAR(10),
            fiscal_date DATE,
            period VARCHAR(20),
            operating_cashflow BIGINT,
            investing_cashflow BIGINT,
            financing_cashflow BIGINT,
            net_change_in_cash BIGINT,
            capital_expenditures BIGINT,
            free_cashflow BIGINT,
            dividends_paid BIGINT,
            stock_repurchased BIGINT,
            depreciation BIGINT,
            fcf_margin DECIMAL(8, 4),
            UNIQUE(symbol, fiscal_date, period)
        )""",

        "CREATE INDEX IF NOT EXISTS idx_cashflow_symbol_date ON fact_cash_flow(symbol, fiscal_date DESC)",

        # Returns
        """CREATE TABLE IF NOT EXISTS fact_returns (
            return_id SERIAL PRIMARY KEY,
            symbol VARCHAR(10),
            calculation_date DATE,
            return_1d DECIMAL(8, 4),
            return_1w DECIMAL(8, 4),
            return_1m DECIMAL(8, 4),
            return_3m DECIMAL(8, 4),
            return_6m DECIMAL(8, 4),
            return_1y DECIMAL(8, 4),
            return_3y DECIMAL(8, 4),
            return_5y DECIMAL(8, 4),
            return_10y DECIMAL(8, 4),
            return_ytd DECIMAL(8, 4),
            volatility_30d DECIMAL(8, 4),
            volatility_90d DECIMAL(8, 4),
            volatility_1y DECIMAL(8, 4),
            sharpe_ratio DECIMAL(8, 4),
            max_drawdown DECIMAL(8, 4),
            UNIQUE(symbol, calculation_date)
        )""",

        "CREATE INDEX IF NOT EXISTS idx_returns_symbol_date ON fact_returns(symbol, calculation_date DESC)",

        # Correlations
        """CREATE TABLE IF NOT EXISTS fact_correlations (
            correlation_id SERIAL PRIMARY KEY,
            symbol_1 VARCHAR(10),
            symbol_2 VARCHAR(10),
            calculation_date DATE,
            correlation_30d DECIMAL(8, 4),
            correlation_90d DECIMAL(8, 4),
            correlation_1y DECIMAL(8, 4),
            correlation_3y DECIMAL(8, 4),
            UNIQUE(symbol_1, symbol_2, calculation_date)
        )""",

        "CREATE INDEX IF NOT EXISTS idx_corr_date ON fact_correlations(calculation_date DESC)",

        # Sector performance
        """CREATE TABLE IF NOT EXISTS fact_sector_performance (
            sector_id SERIAL PRIMARY KEY,
            sector VARCHAR(100),
            calculation_date DATE,
            avg_price_change DECIMAL(8, 4),
            avg_return_1m DECIMAL(8, 4),
            avg_return_1y DECIMAL(8, 4),
            avg_market_cap BIGINT,
            avg_pe_ratio DECIMAL(10, 2),
            total_volume BIGINT,
            num_stocks INT,
            best_performer VARCHAR(10),
            worst_performer VARCHAR(10),
            UNIQUE(sector, calculation_date)
        )""",

        "CREATE INDEX IF NOT EXISTS idx_sector_date ON fact_sector_performance(calculation_date DESC)",

        # Weekly prices
        """CREATE TABLE IF NOT EXISTS fact_weekly_prices (
            weekly_id SERIAL PRIMARY KEY,
            symbol VARCHAR(10),
            week_start_date DATE,
            week_end_date DATE,
            open DECIMAL(12, 4),
            high DECIMAL(12, 4),
            low DECIMAL(12, 4),
            close DECIMAL(12, 4),
            volume BIGINT,
            weekly_return DECIMAL(8, 4),
            UNIQUE(symbol, week_start_date)
        )""",

        "CREATE INDEX IF NOT EXISTS idx_weekly_symbol_date ON fact_weekly_prices(symbol, week_start_date DESC)",

        # Monthly prices
        """CREATE TABLE IF NOT EXISTS fact_monthly_prices (
            monthly_id SERIAL PRIMARY KEY,
            symbol VARCHAR(10),
            month_date DATE,
            open DECIMAL(12, 4),
            high DECIMAL(12, 4),
            low DECIMAL(12, 4),
            close DECIMAL(12, 4),
            volume BIGINT,
            monthly_return DECIMAL(8, 4),
            UNIQUE(symbol, month_date)
        )""",

        "CREATE INDEX IF NOT EXISTS idx_monthly_symbol_date ON fact_monthly_prices(symbol, month_date DESC)",

        # Yearly summary
        """CREATE TABLE IF NOT EXISTS fact_yearly_summary (
            yearly_id SERIAL PRIMARY KEY,
            symbol VARCHAR(10),
            year INT,
            year_open DECIMAL(12, 4),
            year_high DECIMAL(12, 4),
            year_low DECIMAL(12, 4),
            year_close DECIMAL(12, 4),
            total_volume BIGINT,
            year_return DECIMAL(8, 4),
            avg_price DECIMAL(12, 4),
            price_volatility DECIMAL(8, 4),
            UNIQUE(symbol, year)
        )""",

        "CREATE INDEX IF NOT EXISTS idx_yearly_symbol_year ON fact_yearly_summary(symbol, year DESC)",

        # Dividend history
        """CREATE TABLE IF NOT EXISTS fact_dividend_history (
            dividend_id SERIAL PRIMARY KEY,
            symbol VARCHAR(10),
            ex_date DATE NOT NULL,
            dividend_amount DECIMAL(10, 4),
            year INT,
            quarter INT,
            UNIQUE(symbol, ex_date)
        )""",

        "CREATE INDEX IF NOT EXISTS idx_dividend_symbol_date ON fact_dividend_history(symbol, ex_date DESC)",

        # Stock splits
        """CREATE TABLE IF NOT EXISTS fact_stock_splits (
            split_id SERIAL PRIMARY KEY,
            symbol VARCHAR(10),
            split_date DATE NOT NULL,
            split_ratio DECIMAL(10, 4),
            split_description VARCHAR(50),
            UNIQUE(symbol, split_date)
        )""",

        "CREATE INDEX IF NOT EXISTS idx_splits_symbol_date ON fact_stock_splits(symbol, split_date DESC)",

        # Trading signals
        """CREATE TABLE IF NOT EXISTS fact_trading_signals (
            signal_id SERIAL PRIMARY KEY,
            symbol VARCHAR(10),
            signal_date DATE,
            signal_type VARCHAR(20),
            signal_reason VARCHAR(200),
            indicator_value DECIMAL(12, 4),
            created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )""",

        "CREATE INDEX IF NOT EXISTS idx_signals_symbol_date ON fact_trading_signals(symbol, signal_date DESC)",

        # Support & Resistance
        """CREATE TABLE IF NOT EXISTS fact_support_resistance (
            level_id SERIAL PRIMARY KEY,
            symbol VARCHAR(10),
            calculation_date DATE,
            level_type VARCHAR(20),
            price_level DECIMAL(12, 4),
            strength INT
        )""",

        "CREATE INDEX IF NOT EXISTS idx_sr_symbol_date ON fact_support_resistance(symbol, calculation_date DESC)",

        # MA Crossovers
        """CREATE TABLE IF NOT EXISTS fact_ma_crossovers (
            crossover_id SERIAL PRIMARY KEY,
            symbol VARCHAR(10),
            crossover_date DATE,
            crossover_type VARCHAR(50),
            ma_short INT,
            ma_long INT,
            price_at_cross DECIMAL(12, 4)
        )""",

        "CREATE INDEX IF NOT EXISTS idx_crossover_symbol_date ON fact_ma_crossovers(symbol, crossover_date DESC)",

        # Monthly returns heatmap
        """CREATE TABLE IF NOT EXISTS fact_monthly_returns_heatmap (
            heatmap_id SERIAL PRIMARY KEY,
            symbol VARCHAR(10),
            year INT,
            month INT,
            month_name VARCHAR(10),
            return_pct DECIMAL(8, 4),
            start_price DECIMAL(12, 4),
            end_price DECIMAL(12, 4),
            UNIQUE(symbol, year, month)
        )""",

        "CREATE INDEX IF NOT EXISTS idx_heatmap_symbol_year ON fact_monthly_returns_heatmap(symbol, year DESC, month)"
    ]

    success_count = 0
    for query in queries:
        if db.execute_query(query):
            success_count += 1

    logger.info(f"✅ Schema created: {success_count}/{len(queries)} queries executed")
    return success_count == len(queries)

# ============================================
# TECHNICAL ANALYSIS
# ============================================

class TechnicalAnalysis:
    @staticmethod
    def calculate_indicators(df):
        if df.empty or len(df) < 2:
            return df

        try:
            # Moving Averages
            df['ma_20'] = df['Close'].rolling(window=20, min_periods=1).mean()
            df['ma_50'] = df['Close'].rolling(window=50, min_periods=1).mean()
            df['ma_200'] = df['Close'].rolling(window=200, min_periods=1).mean()
            df['ema_12'] = df['Close'].ewm(span=12, adjust=False).mean()
            df['ema_26'] = df['Close'].ewm(span=26, adjust=False).mean()

            # RSI
            delta = df['Close'].diff()
            gain = delta.where(delta > 0, 0).rolling(window=14, min_periods=1).mean()
            loss = -delta.where(delta < 0, 0).rolling(window=14, min_periods=1).mean()
            rs = gain / loss.replace(0, np.nan)
            df['rsi_14'] = 100 - (100 / (1 + rs))

            # MACD
            df['macd'] = df['ema_12'] - df['ema_26']
            df['macd_signal'] = df['macd'].ewm(span=9, adjust=False).mean()
            df['macd_histogram'] = df['macd'] - df['macd_signal']

            # Bollinger Bands
            df['bollinger_middle'] = df['Close'].rolling(window=20, min_periods=1).mean()
            std = df['Close'].rolling(window=20, min_periods=1).std()
            df['bollinger_upper'] = df['bollinger_middle'] + (std * 2)
            df['bollinger_lower'] = df['bollinger_middle'] - (std * 2)
            df['bollinger_width'] = df['bollinger_upper'] - df['bollinger_lower']

            # Stochastic
            low_14 = df['Low'].rolling(window=14, min_periods=1).min()
            high_14 = df['High'].rolling(window=14, min_periods=1).max()
            df['stochastic_k'] = 100 * ((df['Close'] - low_14) / (high_14 - low_14).replace(0, np.nan))
            df['stochastic_d'] = df['stochastic_k'].rolling(window=3, min_periods=1).mean()

            # ATR
            high_low = df['High'] - df['Low']
            high_close = np.abs(df['High'] - df['Close'].shift())
            low_close = np.abs(df['Low'] - df['Close'].shift())
            tr = pd.concat([high_low, high_close, low_close], axis=1).max(axis=1)
            df['atr_14'] = tr.rolling(window=14, min_periods=1).mean()

            # OBV & VWAP
            df['obv'] = (np.sign(df['Close'].diff()) * df['Volume']).fillna(0).cumsum()
            df['vwap'] = (df['Close'] * df['Volume']).cumsum() / df['Volume'].cumsum()

            # Volatility & Returns
            df['volatility_30'] = df['Close'].pct_change().rolling(window=30, min_periods=1).std() * np.sqrt(252)
            df['daily_return'] = df['Close'].pct_change()

            # Volume
            df['avg_volume_20'] = df['Volume'].rolling(window=20, min_periods=1).mean()
            df['volume_ratio'] = df['Volume'] / df['avg_volume_20']

            # Momentum
            df['momentum_10'] = df['Close'].pct_change(periods=10)
            df['momentum_20'] = df['Close'].pct_change(periods=20)

            df = df.fillna(0)
        except Exception as e:
            logger.warning(f"Technical indicators error: {e}")

        return df

    @staticmethod
    def calculate_support_resistance(df, window=20):
        try:
            if len(df) < window:
                return [], []

            high_idx = argrelextrema(df['High'].values, np.greater, order=window)[0]
            low_idx = argrelextrema(df['Low'].values, np.less, order=window)[0]

            resistance = df.iloc[high_idx]['High'].tail(5).tolist() if len(high_idx) > 0 else []
            support = df.iloc[low_idx]['Low'].tail(5).tolist() if len(low_idx) > 0 else []

            return support, resistance
        except:
            return [], []

    @staticmethod
    def generate_trading_signals(df):
        signals = []

        try:
            if len(df) < 50:
                return signals

            latest = df.iloc[-1]
            prev = df.iloc[-2]

            if latest['rsi_14'] < 30:
                signals.append(('BUY', 'RSI Oversold', latest.name, latest['rsi_14']))
            elif latest['rsi_14'] > 70:
                signals.append(('SELL', 'RSI Overbought', latest.name, latest['rsi_14']))

            if prev['macd'] < prev['macd_signal'] and latest['macd'] > latest['macd_signal']:
                signals.append(('BUY', 'MACD Bullish Crossover', latest.name, latest['macd']))
            elif prev['macd'] > prev['macd_signal'] and latest['macd'] < latest['macd_signal']:
                signals.append(('SELL', 'MACD Bearish Crossover', latest.name, latest['macd']))

            if prev['ma_20'] < prev['ma_50'] and latest['ma_20'] > latest['ma_50']:
                signals.append(('BUY', 'Golden Cross (20/50)', latest.name, latest['ma_20']))
            elif prev['ma_20'] > prev['ma_50'] and latest['ma_20'] < latest['ma_50']:
                signals.append(('SELL', 'Death Cross (20/50)', latest.name, latest['ma_20']))

            if latest['Close'] < latest['bollinger_lower']:
                signals.append(('BUY', 'Price Below Lower Band', latest.name, latest['Close']))
            elif latest['Close'] > latest['bollinger_upper']:
                signals.append(('SELL', 'Price Above Upper Band', latest.name, latest['Close']))
        except:
            pass

        return signals

    @staticmethod
    def detect_ma_crossovers(df):
        crossovers = []

        try:
            if len(df) < 200:
                return crossovers

            recent_df = df.tail(504)

            for i in range(1, len(recent_df)):
                curr = recent_df.iloc[i]
                prev = recent_df.iloc[i-1]

                if prev['ma_50'] <= prev['ma_200'] and curr['ma_50'] > curr['ma_200']:
                    crossovers.append({
                        'date': curr.name, 'type': 'Golden Cross',
                        'ma_short': 50, 'ma_long': 200, 'price': curr['Close']
                    })
                elif prev['ma_50'] >= prev['ma_200'] and curr['ma_50'] < curr['ma_200']:
                    crossovers.append({
                        'date': curr.name, 'type': 'Death Cross',
                        'ma_short': 50, 'ma_long': 200, 'price': curr['Close']
                    })

                if prev['ma_20'] <= prev['ma_50'] and curr['ma_20'] > curr['ma_50']:
                    crossovers.append({
                        'date': curr.name, 'type': 'Bullish Cross',
                        'ma_short': 20, 'ma_long': 50, 'price': curr['Close']
                    })
                elif prev['ma_20'] >= prev['ma_50'] and curr['ma_20'] < curr['ma_50']:
                    crossovers.append({
                        'date': curr.name, 'type': 'Bearish Cross',
                        'ma_short': 20, 'ma_long': 50, 'price': curr['Close']
                    })
        except:
            pass

        return crossovers

# ============================================
# DATA COLLECTION
# ============================================

class StockDataCollector:
    def __init__(self, config):
        self.config = config
        self.ta = TechnicalAnalysis()

    def download_logo(self, symbol):
        try:
            domain = self.config.COMPANY_DOMAINS.get(symbol, '')
            if not domain:
                return None, None

            logo_url = f"https://logo.clearbit.com/{domain}"
            response = requests.get(logo_url, timeout=10)

            if response.status_code == 200:
                img = Image.open(BytesIO(response.content))
                img = img.convert('RGBA')
                img = img.resize((128, 128), Image.Resampling.LANCZOS)

                buffered = BytesIO()
                img.save(buffered, format="PNG")
                img_str = base64.b64encode(buffered.getvalue()).decode('utf-8')

                return f"logo_{symbol}.png", img_str

            return None, None
        except:
            return None, None

    def get_dividend_split_history(self, stock, symbol):
        dividends_list = []
        splits_list = []

        try:
            dividends = stock.dividends
            if not dividends.empty:
                for date, amount in dividends.items():
                    if date.year >= 2015:
                        dividends_list.append({
                            'symbol': symbol,
                            'ex_date': date.date(),
                            'dividend_amount': float(amount),
                            'year': date.year,
                            'quarter': (date.month - 1) // 3 + 1
                        })

            splits = stock.splits
            if not splits.empty:
                for date, ratio in splits.items():
                    if date.year >= 2015:
                        splits_list.append({
                            'symbol': symbol,
                            'split_date': date.date(),
                            'split_ratio': float(ratio),
                            'split_description': f"{int(ratio)}:1" if ratio > 1 else f"1:{int(1/ratio)}"
                        })
        except:
            pass

        return dividends_list, splits_list

    def create_monthly_returns_heatmap(self, df, symbol):
        if df.empty:
            return []

        monthly_returns = []

        try:
            df_copy = df.copy()
            df_copy['year'] = df_copy.index.year
            df_copy['month'] = df_copy.index.month

            for year in range(2015, 2026):
                year_data = df_copy[df_copy['year'] == year]

                for month in range(1, 13):
                    month_data = year_data[year_data['month'] == month]

                    if len(month_data) > 0:
                        month_return = (month_data['Close'].iloc[-1] - month_data['Close'].iloc[0]) / month_data['Close'].iloc[0]

                        monthly_returns.append({
                            'symbol': symbol,
                            'year': year,
                            'month': month,
                            'month_name': pd.to_datetime(f'{year}-{month:02d}-01').strftime('%b'),
                            'return_pct': month_return * 100,
                            'start_price': month_data['Close'].iloc[0],
                            'end_price': month_data['Close'].iloc[-1]
                        })
        except:
            pass

        return monthly_returns

    def collect_stock_data(self, symbol):
        for attempt in range(self.config.MAX_RETRIES):
            try:
                stock = yf.Ticker(symbol)
                info = stock.info

                hist = stock.history(period=self.config.HISTORY_PERIOD)

                if hist.empty:
                    raise ValueError(f"No historical data for {symbol}")

                income_stmt = stock.quarterly_financials
                balance_sheet = stock.quarterly_balance_sheet
                cashflow = stock.quarterly_cashflow

                dividends, splits = self.get_dividend_split_history(stock, symbol)

                logo_path, logo_base64 = self.download_logo(symbol)

                hist = self.ta.calculate_indicators(hist)

                support, resistance = self.ta.calculate_support_resistance(hist)

                signals = self.ta.generate_trading_signals(hist)

                crossovers = self.ta.detect_ma_crossovers(hist)

                monthly_returns = self.create_monthly_returns_heatmap(hist, symbol)

                return {
                    'symbol': symbol,
                    'info': info,
                    'history': hist,
                    'income_statement': income_stmt,
                    'balance_sheet': balance_sheet,
                    'cashflow': cashflow,
                    'dividends': dividends,
                    'splits': splits,
                    'support_levels': support,
                    'resistance_levels': resistance,
                    'trading_signals': signals,
                    'ma_crossovers': crossovers,
                    'monthly_returns': monthly_returns,
                    'logo_path': logo_path,
                    'logo_base64': logo_base64,
                    'success': True
                }

            except Exception as e:
                if attempt < self.config.MAX_RETRIES - 1:
                    logger.warning(f"⚠️ {symbol} attempt {attempt + 1} failed, retrying...")
                    time.sleep(self.config.RETRY_DELAY)
                    continue
                else:
                    logger.error(f"❌ {symbol} failed after {self.config.MAX_RETRIES} attempts: {e}")
                    return {'symbol': symbol, 'success': False}

        return {'symbol': symbol, 'success': False}

# ============================================
# DATA PROCESSING
# ============================================

class DataProcessor:
    @staticmethod
    def calculate_returns(df, symbol):
        if df.empty or len(df) < 2:
            return None

        try:
            returns = {
                'symbol': symbol,
                'calculation_date': df.index[-1].date(),
                'return_1d': (df['Close'].iloc[-1] - df['Close'].iloc[-2]) / df['Close'].iloc[-2] if len(df) >= 2 else 0,
                'return_1w': (df['Close'].iloc[-1] - df['Close'].iloc[-5]) / df['Close'].iloc[-5] if len(df) >= 5 else 0,
                'return_1m': (df['Close'].iloc[-1] - df['Close'].iloc[-21]) / df['Close'].iloc[-21] if len(df) >= 21 else 0,
                'return_3m': (df['Close'].iloc[-1] - df['Close'].iloc[-63]) / df['Close'].iloc[-63] if len(df) >= 63 else 0,
                'return_6m': (df['Close'].iloc[-1] - df['Close'].iloc[-126]) / df['Close'].iloc[-126] if len(df) >= 126 else 0,
                'return_1y': (df['Close'].iloc[-1] - df['Close'].iloc[-252]) / df['Close'].iloc[-252] if len(df) >= 252 else 0,
                'return_3y': (df['Close'].iloc[-1] - df['Close'].iloc[-756]) / df['Close'].iloc[-756] if len(df) >= 756 else 0,
                'return_5y': (df['Close'].iloc[-1] - df['Close'].iloc[-1260]) / df['Close'].iloc[-1260] if len(df) >= 1260 else 0,
                'return_10y': (df['Close'].iloc[-1] - df['Close'].iloc[-2520]) / df['Close'].iloc[-2520] if len(df) >= 2520 else 0,
                'return_ytd': 0,
                'volatility_30d': df['Close'].pct_change().tail(30).std() * np.sqrt(252) if len(df) >= 30 else 0,
                'volatility_90d': df['Close'].pct_change().tail(90).std() * np.sqrt(252) if len(df) >= 90 else 0,
                'volatility_1y': df['Close'].pct_change().tail(252).std() * np.sqrt(252) if len(df) >= 252 else 0,
                'sharpe_ratio': 0,
                'max_drawdown': 0
            }

            current_year = df.index[-1].year
            ytd_data = df[df.index.year == current_year]
            if len(ytd_data) > 0:
                returns['return_ytd'] = (df['Close'].iloc[-1] - ytd_data['Close'].iloc[0]) / ytd_data['Close'].iloc[0]

            if len(df) >= 252:
                daily_returns = df['Close'].pct_change().tail(252)
                excess_returns = daily_returns - (0.02 / 252)
                if daily_returns.std() > 0:
                    returns['sharpe_ratio'] = (excess_returns.mean() / daily_returns.std()) * np.sqrt(252)

            rolling_max = df['Close'].cummax()
            drawdown = (df['Close'] - rolling_max) / rolling_max
            returns['max_drawdown'] = drawdown.min()

            return returns
        except:
            return None

    @staticmethod
    def calculate_correlations(price_dict):
        correlations = []
        price_df = pd.DataFrame()

        for symbol, df in price_dict.items():
            if not df.empty and 'close' in df.columns:
                price_df[symbol] = df.set_index('trading_date')['close']

        if not price_df.empty and len(price_df.columns) >= 2:
            symbols = price_df.columns.tolist()
            calc_date = price_df.index[-1] if len(price_df) > 0 else datetime.now().date()

            for i, sym1 in enumerate(symbols):
                for sym2 in symbols[i+1:]:
                    try:
                        corr_30d = price_df[[sym1, sym2]].tail(30).corr().iloc[0, 1] if len(price_df) >= 30 else 0
                        corr_90d = price_df[[sym1, sym2]].tail(90).corr().iloc[0, 1] if len(price_df) >= 90 else 0
                        corr_1y = price_df[[sym1, sym2]].tail(252).corr().iloc[0, 1] if len(price_df) >= 252 else 0
                        corr_3y = price_df[[sym1, sym2]].tail(756).corr().iloc[0, 1] if len(price_df) >= 756 else 0

                        correlations.append({
                            'symbol_1': sym1, 'symbol_2': sym2, 'calculation_date': calc_date,
                            'correlation_30d': corr_30d, 'correlation_90d': corr_90d,
                            'correlation_1y': corr_1y, 'correlation_3y': corr_3y
                        })
                    except:
                        pass

        return correlations

    @staticmethod
    def calculate_sector_performance(all_data):
        sector_perf = []

        try:
            quotes_df = pd.DataFrame(all_data['quotes'])
            fundamentals_df = pd.DataFrame(all_data['fundamentals'])
            stock_info_df = pd.DataFrame(all_data['stock_info'])

            if quotes_df.empty or stock_info_df.empty:
                return sector_perf

            merged = quotes_df.merge(stock_info_df[['symbol', 'sector']], on='symbol', how='left')

            if 'market_cap' not in merged.columns and not fundamentals_df.empty and 'market_cap' in fundamentals_df.columns:
                merged = merged.merge(fundamentals_df[['symbol', 'market_cap']], on='symbol', how='left', suffixes=('', '_fund'))

            if not fundamentals_df.empty and 'trailing_pe' in fundamentals_df.columns:
                merged = merged.merge(fundamentals_df[['symbol', 'trailing_pe']], on='symbol', how='left', suffixes=('', '_pe'))

            for sector in merged['sector'].unique():
                if pd.isna(sector) or sector == 'Unknown' or sector == '':
                    continue

                sector_data = merged[merged['sector'] == sector]

                avg_market_cap = 0
                if 'market_cap' in sector_data.columns:
                    avg_market_cap = sector_data['market_cap'].mean()

                avg_pe = 0
                if 'trailing_pe' in sector_data.columns:
                    avg_pe = sector_data['trailing_pe'].mean()

                avg_change = 0
                if 'change_percent' in sector_data.columns:
                    avg_change = sector_data['change_percent'].mean()

                total_vol = 0
                if 'volume' in sector_data.columns:
                    total_vol = sector_data['volume'].sum()

                best_performer = ''
                worst_performer = ''
                if 'change_percent' in sector_data.columns and len(sector_data) > 0:
                    try:
                        best_performer = sector_data.loc[sector_data['change_percent'].idxmax(), 'symbol']
                        worst_performer = sector_data.loc[sector_data['change_percent'].idxmin(), 'symbol']
                    except:
                        pass

                sector_perf.append({
                    'sector': sector,
                    'calculation_date': datetime.now().date(),
                    'avg_price_change': float(avg_change) if pd.notna(avg_change) else 0,
                    'avg_return_1m': 0,
                    'avg_return_1y': 0,
                    'avg_market_cap': int(avg_market_cap) if pd.notna(avg_market_cap) else 0,
                    'avg_pe_ratio': float(avg_pe) if pd.notna(avg_pe) else 0,
                    'total_volume': int(total_vol) if pd.notna(total_vol) else 0,
                    'num_stocks': len(sector_data),
                    'best_performer': best_performer,
                    'worst_performer': worst_performer
                })
        except Exception as e:
            logger.warning(f"Sector performance calculation error: {e}")

        return sector_perf

# ============================================
# DATABASE INSERTION
# ============================================

class DataInserter:
    def __init__(self, db):
        self.db = db

    def insert_stock_info(self, data):
        query = """
        INSERT INTO dim_stocks (symbol, company_name, display_name, logo_base64,
            logo_file_path, sector, industry, website, description, country,
            currency, exchange, employees, market_cap)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (symbol) DO UPDATE SET
            company_name = EXCLUDED.company_name,
            logo_base64 = EXCLUDED.logo_base64,
            logo_file_path = EXCLUDED.logo_file_path,
            sector = EXCLUDED.sector,
            industry = EXCLUDED.industry,
            updated_date = CURRENT_TIMESTAMP
        """

        records = [
            (
                row['symbol'], row['company_name'], row['display_name'],
                row['logo_base64'], row['logo_file_path'], row['sector'],
                row['industry'], row['website'], row['description'],
                row['country'], row['currency'], row['exchange'],
                row['employees'], row['market_cap']
            )
            for row in data
        ]

        return self.db.batch_insert(query, records)

    def insert_daily_prices(self, df):
        if df.empty:
            return 0

        query = """
        INSERT INTO fact_daily_prices (symbol, trading_date, open, high, low, close,
            adjusted_close, volume, dividends, stock_splits, ma_20, ma_50, ma_200,
            ema_12, ema_26, rsi_14, macd, macd_signal, macd_histogram,
            bollinger_upper, bollinger_middle, bollinger_lower, bollinger_width,
            stochastic_k, stochastic_d, atr_14, obv, vwap, volatility_30,
            daily_return, avg_volume_20, volume_ratio, momentum_10, momentum_20)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
            %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (symbol, trading_date) DO UPDATE SET
            close = EXCLUDED.close,
            volume = EXCLUDED.volume,
            ma_20 = EXCLUDED.ma_20,
            rsi_14 = EXCLUDED.rsi_14
        """

        records = []
        for _, row in df.iterrows():
            records.append((
                row['symbol'], row['trading_date'], row.get('open', 0),
                row.get('high', 0), row.get('low', 0), row.get('close', 0),
                row.get('adjusted_close', 0), row.get('volume', 0),
                row.get('dividends', 0), row.get('stock_splits', 0),
                row.get('ma_20', 0), row.get('ma_50', 0), row.get('ma_200', 0),
                row.get('ema_12', 0), row.get('ema_26', 0), row.get('rsi_14', 0),
                row.get('macd', 0), row.get('macd_signal', 0),
                row.get('macd_histogram', 0), row.get('bollinger_upper', 0),
                row.get('bollinger_middle', 0), row.get('bollinger_lower', 0),
                row.get('bollinger_width', 0), row.get('stochastic_k', 0),
                row.get('stochastic_d', 0), row.get('atr_14', 0),
                row.get('obv', 0), row.get('vwap', 0),
                row.get('volatility_30', 0), row.get('daily_return', 0),
                row.get('avg_volume_20', 0), row.get('volume_ratio', 0),
                row.get('momentum_10', 0), row.get('momentum_20', 0)
            ))

        return self.db.batch_insert(query, records, page_size=500)

    def insert_generic_table(self, table_name, df, conflict_clause=""):
        if df.empty:
            return 0

        columns = list(df.columns)
        placeholders = ', '.join(['%s'] * len(columns))
        cols_str = ', '.join(columns)

        query = f"""
        INSERT INTO {table_name} ({cols_str})
        VALUES ({placeholders})
        {conflict_clause}
        """

        records = [tuple(row[c] for c in columns) for _, row in df.iterrows()]

        return self.db.batch_insert(query, records, page_size=500)

# ============================================
# MAIN PIPELINE
# ============================================

class StockPipeline:
    def __init__(self, config):
        self.config = config
        self.db = DatabaseManager(config.DB_CONFIG)
        self.collector = StockDataCollector(config)
        self.processor = DataProcessor()
        self.inserter = None
        self.insertion_results = {}

    def run(self):
        logger.info("=" * 80)
        logger.info("🚀 ENHANCED STOCK PIPELINE v3.0 - GOOGLE COLAB EDITION")
        logger.info("=" * 80)
        logger.info(f"📅 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        logger.info(f"📊 {len(self.config.get_all_stocks())} stocks × 10 years")
        logger.info("=" * 80)

        if not self.config.validate_db_config():
            logger.error("❌ Invalid database configuration!")
            return False

        if not self.db.connect():
            return False

        self.inserter = DataInserter(self.db)

        if not create_database_schema(self.db):
            logger.error("❌ Failed to create database schema")
            self.db.disconnect()
            return False

        all_data = self.collect_all_stocks()

        self.insert_all_data(all_data)

        verification_results = self.verify_all_data()

        self.print_summary(all_data)

        # Print final summary box
        self.print_final_summary(verification_results)

        self.db.disconnect()

        logger.info("=" * 80)
        logger.info("✅ PIPELINE COMPLETED SUCCESSFULLY!")
        logger.info("=" * 80)

        return True

    def collect_all_stocks(self):
        logger.info("\n📊 Collecting stock data...")

        all_data = {
            'stock_info': [], 'quotes': [], 'fundamentals': [],
            'historical': [], 'income_statements': [], 'balance_sheets': [],
            'cashflows': [], 'returns': [], 'weekly': [], 'monthly': [],
            'yearly': [], 'dividends': [], 'splits': [],
            'trading_signals': [], 'support_resistance': [],
            'ma_crossovers': [], 'monthly_returns_heatmap': [],
            'correlations': [], 'sector_performance': [], 'price_dict': {}
        }

        stocks = self.config.get_all_stocks()
        success_count = 0
        failed_stocks = []

        for symbol in tqdm(stocks, desc="Processing stocks"):
            data = self.collector.collect_stock_data(symbol)

            if not data['success']:
                failed_stocks.append(symbol)
                continue

            success_count += 1
            self._extract_stock_data(symbol, data, all_data)

        # DEBUG: Print sample data
        logger.info(f"\n✅ Successfully collected data for {success_count}/{len(stocks)} stocks")
        if failed_stocks:
            logger.warning(f"❌ Failed stocks: {', '.join(failed_stocks)}")

        logger.info("\n🔍 Sample data check:")
        logger.info(f"   Stock info entries: {len(all_data['stock_info'])}")
        logger.info(f"   Quotes entries: {len(all_data['quotes'])}")
        logger.info(f"   Fundamentals entries: {len(all_data['fundamentals'])}")
        logger.info(f"   Historical DataFrames: {len(all_data['historical'])}")
        logger.info(f"   Income statements: {len(all_data['income_statements'])}")
        logger.info(f"   Balance sheets: {len(all_data['balance_sheets'])}")
        logger.info(f"   Cash flows: {len(all_data['cashflows'])}")
        logger.info(f"   Returns: {len(all_data['returns'])}")
        logger.info(f"   Dividends: {len(all_data['dividends'])}")
        logger.info(f"   Splits: {len(all_data['splits'])}")
        logger.info(f"   Trading signals: {len(all_data['trading_signals'])}")
        logger.info(f"   MA crossovers: {len(all_data['ma_crossovers'])}")
        logger.info(f"   Monthly returns heatmap: {len(all_data['monthly_returns_heatmap'])}")

        # Print sample of first stock's data
        if all_data['quotes']:
            logger.info(f"\n📋 Sample quote data (first stock):")
            logger.info(f"   {all_data['quotes'][0]}")
        if all_data['fundamentals']:
            logger.info(f"\n📋 Sample fundamental data (first stock):")
            sample = all_data['fundamentals'][0]
            logger.info(f"   Symbol: {sample.get('symbol')}, Market Cap: {sample.get('market_cap')}, PE: {sample.get('trailing_pe')}")

        logger.info("\n📊 Calculating correlations...")
        all_data['correlations'] = self.processor.calculate_correlations(all_data['price_dict'])
        logger.info(f"   Correlations calculated: {len(all_data['correlations'])}")

        logger.info("📊 Calculating sector performance...")
        all_data['sector_performance'] = self.processor.calculate_sector_performance(all_data)
        logger.info(f"   Sector performance entries: {len(all_data['sector_performance'])}")

        return all_data

    def _extract_stock_data(self, symbol, data, all_data):
        info = data['info']
        hist = data['history']

        all_data['stock_info'].append({
            'symbol': symbol,
            'company_name': info.get('longName', self.config.COMPANY_NAMES.get(symbol, symbol)),
            'display_name': self.config.COMPANY_NAMES.get(symbol, info.get('longName', symbol)),
            'logo_base64': data.get('logo_base64', ''),
            'logo_file_path': data.get('logo_path', ''),
            'sector': info.get('sector', 'Unknown'),
            'industry': info.get('industry', 'Unknown'),
            'website': info.get('website', ''),
            'description': info.get('longBusinessSummary', ''),
            'country': info.get('country', ''),
            'currency': info.get('currency', 'USD'),
            'exchange': info.get('exchange', ''),
            'employees': info.get('fullTimeEmployees', 0),
            'market_cap': info.get('marketCap', 0)
        })

        all_data['dividends'].extend(data.get('dividends', []))
        all_data['splits'].extend(data.get('splits', []))
        all_data['monthly_returns_heatmap'].extend(data.get('monthly_returns', []))

        for signal_type, reason, date, value in data.get('trading_signals', []):
            all_data['trading_signals'].append({
                'symbol': symbol,
                'signal_date': pd.to_datetime(date).date() if isinstance(date, pd.Timestamp) else datetime.now().date(),
                'signal_type': signal_type,
                'signal_reason': reason,
                'indicator_value': float(value)
            })

        calc_date = datetime.now().date()
        for i, level in enumerate(data.get('support_levels', [])):
            all_data['support_resistance'].append({
                'symbol': symbol, 'calculation_date': calc_date,
                'level_type': 'Support', 'price_level': float(level),
                'strength': len(data.get('support_levels', [])) - i
            })

        for i, level in enumerate(data.get('resistance_levels', [])):
            all_data['support_resistance'].append({
                'symbol': symbol, 'calculation_date': calc_date,
                'level_type': 'Resistance', 'price_level': float(level),
                'strength': len(data.get('resistance_levels', [])) - i
            })

        for crossover in data.get('ma_crossovers', []):
            all_data['ma_crossovers'].append({
                'symbol': symbol,
                'crossover_date': pd.to_datetime(crossover['date']).date(),
                'crossover_type': crossover['type'],
                'ma_short': crossover['ma_short'],
                'ma_long': crossover['ma_long'],
                'price_at_cross': float(crossover['price'])
            })

        if not hist.empty:
            hist_processed = hist.copy()
            hist_processed['symbol'] = symbol
            hist_processed['trading_date'] = hist_processed.index

            rename_map = {
                'Open': 'open', 'High': 'high', 'Low': 'low',
                'Close': 'close', 'Volume': 'volume',
                'Dividends': 'dividends', 'Stock Splits': 'stock_splits'
            }
            hist_processed = hist_processed.rename(columns=rename_map)

            if 'adjusted_close' not in hist_processed.columns:
                hist_processed['adjusted_close'] = hist_processed.get('close', 0)

            all_data['historical'].append(hist_processed)
            all_data['price_dict'][symbol] = hist_processed

            returns = self.processor.calculate_returns(hist, symbol)
            if returns:
                all_data['returns'].append(returns)

            weekly = hist.resample('W').agg({
                'Open': 'first', 'High': 'max', 'Low': 'min',
                'Close': 'last', 'Volume': 'sum'
            })
            weekly['symbol'] = symbol
            weekly['week_start_date'] = weekly.index - pd.Timedelta(days=6)
            weekly['week_end_date'] = weekly.index
            weekly['weekly_return'] = weekly['Close'].pct_change()
            weekly = weekly.rename(columns={
                'Open': 'open', 'High': 'high', 'Low': 'low',
                'Close': 'close', 'Volume': 'volume'
            })
            all_data['weekly'].append(weekly.reset_index(drop=True))

            monthly = hist.resample('M').agg({
                'Open': 'first', 'High': 'max', 'Low': 'min',
                'Close': 'last', 'Volume': 'sum'
            })
            monthly['symbol'] = symbol
            monthly['month_date'] = monthly.index
            monthly['monthly_return'] = monthly['Close'].pct_change()
            monthly = monthly.rename(columns={
                'Open': 'open', 'High': 'high', 'Low': 'low',
                'Close': 'close', 'Volume': 'volume'
            })
            all_data['monthly'].append(monthly.reset_index(drop=True))

            yearly = hist.resample('Y').agg({
                'Open': 'first', 'High': 'max', 'Low': 'min',
                'Close': 'last', 'Volume': 'sum'
            })
            yearly['symbol'] = symbol
            yearly['year'] = yearly.index.year
            yearly['year_return'] = yearly['Close'].pct_change()
            yearly['avg_price'] = hist.resample('Y')['Close'].mean().values
            yearly['price_volatility'] = hist.resample('Y')['Close'].std().values
            yearly = yearly.rename(columns={
                'Open': 'year_open', 'High': 'year_high', 'Low': 'year_low',
                'Close': 'year_close', 'Volume': 'total_volume'
            })
            all_data['yearly'].append(yearly.reset_index(drop=True))

        all_data['quotes'].append({
            'symbol': symbol,
            'fetch_timestamp': datetime.now(),
            'trading_date': datetime.now().date(),
            'current_price': info.get('currentPrice', info.get('regularMarketPrice', 0)),
            'price_change': info.get('regularMarketChange', 0),
            'change_percent': info.get('regularMarketChangePercent', 0),
            'volume': info.get('volume', 0),
            'open': info.get('regularMarketOpen', 0),
            'high': info.get('dayHigh', 0),
            'low': info.get('dayLow', 0),
            'previous_close': info.get('previousClose', 0),
            'market_cap': info.get('marketCap', 0),
            'avg_volume': info.get('averageVolume', 0),
            'day_range': f"{info.get('dayLow', 0)} - {info.get('dayHigh', 0)}"
        })

        all_data['fundamentals'].append({
            'symbol': symbol,
            'market_cap': info.get('marketCap', 0),
            'enterprise_value': info.get('enterpriseValue', 0),
            'trailing_pe': info.get('trailingPE', 0),
            'forward_pe': info.get('forwardPE', 0),
            'peg_ratio': info.get('pegRatio', 0),
            'price_to_book': info.get('priceToBook', 0),
            'price_to_sales': info.get('priceToSalesTrailing12Months', 0),
            'enterprise_to_revenue': info.get('enterpriseToRevenue', 0),
            'enterprise_to_ebitda': info.get('enterpriseToEbitda', 0),
            'profit_margin': info.get('profitMargins', 0),
            'operating_margin': info.get('operatingMargins', 0),
            'return_on_assets': info.get('returnOnAssets', 0),
            'return_on_equity': info.get('returnOnEquity', 0),
            'revenue': info.get('totalRevenue', 0),
            'revenue_per_share': info.get('revenuePerShare', 0),
            'gross_profit': info.get('grossProfits', 0),
            'ebitda': info.get('ebitda', 0),
            'net_income': info.get('netIncomeToCommon', 0),
            'eps': info.get('trailingEps', 0),
            'book_value': info.get('bookValue', 0),
            'dividend_rate': info.get('dividendRate', 0),
            'dividend_yield': info.get('dividendYield', 0),
            'payout_ratio': info.get('payoutRatio', 0),
            'beta': info.get('beta', 0),
            'week_52_high': info.get('fiftyTwoWeekHigh', 0),
            'week_52_low': info.get('fiftyTwoWeekLow', 0),
            'fifty_day_avg': info.get('fiftyDayAverage', 0),
            'two_hundred_day_avg': info.get('twoHundredDayAverage', 0),
            'shares_outstanding': info.get('sharesOutstanding', 0),
            'float_shares': info.get('floatShares', 0),
            'shares_short': info.get('sharesShort', 0),
            'short_ratio': info.get('shortRatio', 0),
            'held_percent_institutions': info.get('heldPercentInstitutions', 0),
            'held_percent_insiders': info.get('heldPercentInsiders', 0)
        })

        self._extract_financial_statements(symbol, data, all_data)

    def _extract_financial_statements(self, symbol, data, all_data):
        if data['income_statement'] is not None and not data['income_statement'].empty:
            income_df = data['income_statement'].T
            for idx, row in income_df.iterrows():
                try:
                    total_rev = row.get('Total Revenue', row.get('TotalRevenue', 0))
                    cost_rev = row.get('Cost Of Revenue', row.get('CostOfRevenue', 0))
                    gross_profit = row.get('Gross Profit', row.get('GrossProfit', 0))
                    op_income = row.get('Operating Income', row.get('OperatingIncome', 0))
                    net_income = row.get('Net Income', row.get('NetIncome', 0))
                    ebitda = row.get('EBITDA', row.get('Ebitda', 0))

                    all_data['income_statements'].append({
                        'symbol': symbol,
                        'fiscal_date': pd.to_datetime(idx).date(),
                        'period': 'Quarterly',
                        'total_revenue': int(total_rev) if pd.notna(total_rev) else 0,
                        'cost_of_revenue': int(cost_rev) if pd.notna(cost_rev) else 0,
                        'gross_profit': int(gross_profit) if pd.notna(gross_profit) else 0,
                        'research_development': int(row.get('Research And Development', 0)) if pd.notna(row.get('Research And Development')) else 0,
                        'selling_general_admin': int(row.get('Selling General And Administration', 0)) if pd.notna(row.get('Selling General And Administration')) else 0,
                        'operating_expenses': int(row.get('Operating Expense', 0)) if pd.notna(row.get('Operating Expense')) else 0,
                        'operating_income': int(op_income) if pd.notna(op_income) else 0,
                        'interest_expense': int(row.get('Interest Expense', 0)) if pd.notna(row.get('Interest Expense')) else 0,
                        'other_income_expense': 0,
                        'income_before_tax': int(row.get('Income Before Tax', 0)) if pd.notna(row.get('Income Before Tax')) else 0,
                        'income_tax_expense': int(row.get('Tax Provision', 0)) if pd.notna(row.get('Tax Provision')) else 0,
                        'net_income': int(net_income) if pd.notna(net_income) else 0,
                        'ebitda': int(ebitda) if pd.notna(ebitda) else 0,
                        'basic_eps': 0,
                        'diluted_eps': 0,
                        'gross_margin': float(gross_profit / total_rev) if total_rev > 0 else 0,
                        'operating_margin': float(op_income / total_rev) if total_rev > 0 else 0,
                        'net_margin': float(net_income / total_rev) if total_rev > 0 else 0,
                        'ebitda_margin': float(ebitda / total_rev) if total_rev > 0 else 0
                    })
                except:
                    pass

        if data['balance_sheet'] is not None and not data['balance_sheet'].empty:
            balance_df = data['balance_sheet'].T
            for idx, row in balance_df.iterrows():
                try:
                    total_assets = row.get('Total Assets', row.get('TotalAssets', 0))
                    current_assets = row.get('Current Assets', row.get('CurrentAssets', 0))
                    total_liabilities = row.get('Total Liabilities Net Minority Interest', 0)
                    current_liabilities = row.get('Current Liabilities', row.get('CurrentLiabilities', 0))
                    total_equity = row.get('Total Equity Gross Minority Interest', row.get('StockholdersEquity', 0))
                    long_term_debt = row.get('Long Term Debt', row.get('LongTermDebt', 0))
                    short_term_debt = row.get('Current Debt', row.get('CurrentDebt', 0))
                    cash = row.get('Cash And Cash Equivalents', row.get('CashAndCashEquivalents', 0))

                    total_debt = (long_term_debt if pd.notna(long_term_debt) else 0) + (short_term_debt if pd.notna(short_term_debt) else 0)

                    all_data['balance_sheets'].append({
                        'symbol': symbol,
                        'fiscal_date': pd.to_datetime(idx).date(),
                        'period': 'Quarterly',
                        'total_assets': int(total_assets) if pd.notna(total_assets) else 0,
                        'current_assets': int(current_assets) if pd.notna(current_assets) else 0,
                        'cash_and_equivalents': int(cash) if pd.notna(cash) else 0,
                        'accounts_receivable': int(row.get('Accounts Receivable', 0)) if pd.notna(row.get('Accounts Receivable')) else 0,
                        'inventory': int(row.get('Inventory', 0)) if pd.notna(row.get('Inventory')) else 0,
                        'property_plant_equipment': int(row.get('Net PPE', 0)) if pd.notna(row.get('Net PPE')) else 0,
                        'goodwill': int(row.get('Goodwill', 0)) if pd.notna(row.get('Goodwill')) else 0,
                        'total_liabilities': int(total_liabilities) if pd.notna(total_liabilities) else 0,
                        'current_liabilities': int(current_liabilities) if pd.notna(current_liabilities) else 0,
                        'accounts_payable': int(row.get('Accounts Payable', 0)) if pd.notna(row.get('Accounts Payable')) else 0,
                        'short_term_debt': int(short_term_debt) if pd.notna(short_term_debt) else 0,
                        'long_term_debt': int(long_term_debt) if pd.notna(long_term_debt) else 0,
                        'total_equity': int(total_equity) if pd.notna(total_equity) else 0,
                        'retained_earnings': int(row.get('Retained Earnings', 0)) if pd.notna(row.get('Retained Earnings')) else 0,
                        'working_capital': int(current_assets - current_liabilities) if pd.notna(current_assets) and pd.notna(current_liabilities) else 0,
                        'total_debt': int(total_debt),
                        'net_debt': int(total_debt - cash) if pd.notna(cash) else int(total_debt),
                        'current_ratio': float(current_assets / current_liabilities) if current_liabilities > 0 else 0,
                        'debt_to_equity': float(total_debt / total_equity) if total_equity > 0 else 0,
                        'debt_to_assets': float(total_debt / total_assets) if total_assets > 0 else 0
                    })
                except:
                    pass

        if data['cashflow'] is not None and not data['cashflow'].empty:
            cashflow_df = data['cashflow'].T
            for idx, row in cashflow_df.iterrows():
                try:
                    operating_cf = row.get('Operating Cash Flow', row.get('OperatingCashFlow', 0))
                    capex = row.get('Capital Expenditure', row.get('CapitalExpenditure', 0))

                    all_data['cashflows'].append({
                        'symbol': symbol,
                        'fiscal_date': pd.to_datetime(idx).date(),
                        'period': 'Quarterly',
                        'operating_cashflow': int(operating_cf) if pd.notna(operating_cf) else 0,
                        'investing_cashflow': int(row.get('Investing Cash Flow', 0)) if pd.notna(row.get('Investing Cash Flow')) else 0,
                        'financing_cashflow': int(row.get('Financing Cash Flow', 0)) if pd.notna(row.get('Financing Cash Flow')) else 0,
                        'net_change_in_cash': int(row.get('Changes In Cash', 0)) if pd.notna(row.get('Changes In Cash')) else 0,
                        'capital_expenditures': int(capex) if pd.notna(capex) else 0,
                        'free_cashflow': int(operating_cf - abs(capex)) if pd.notna(operating_cf) and pd.notna(capex) else 0,
                        'dividends_paid': int(row.get('Cash Dividends Paid', 0)) if pd.notna(row.get('Cash Dividends Paid')) else 0,
                        'stock_repurchased': int(row.get('Repurchase Of Capital Stock', 0)) if pd.notna(row.get('Repurchase Of Capital Stock')) else 0,
                        'depreciation': int(row.get('Depreciation And Amortization', 0)) if pd.notna(row.get('Depreciation And Amortization')) else 0,
                        'fcf_margin': 0
                    })
                except:
                    pass

    def insert_all_data(self, all_data):
        logger.info("\n💾 Inserting data into database...")

        # Debug: Print what data we collected
        logger.info("\n🔍 DEBUG - Data Collection Summary:")
        for key, value in all_data.items():
            if key == 'price_dict':
                continue
            if isinstance(value, list):
                logger.info(f"   {key}: {len(value)} items")
            elif isinstance(value, dict):
                logger.info(f"   {key}: {len(value)} keys")

        dataframes = {}
        for key in ['historical', 'weekly', 'monthly', 'yearly']:
            if all_data[key]:
                try:
                    dataframes[key] = pd.concat(all_data[key], ignore_index=True)
                    logger.info(f"✅ {key} DataFrame created: {len(dataframes[key])} rows")
                except Exception as e:
                    logger.error(f"❌ Error creating {key} DataFrame: {e}")
                    dataframes[key] = pd.DataFrame()
            else:
                dataframes[key] = pd.DataFrame()
                logger.warning(f"⚠️ {key}: Empty list, no data to concat")

        for key in ['stock_info', 'quotes', 'fundamentals', 'income_statements',
                   'balance_sheets', 'cashflows', 'returns', 'dividends', 'splits',
                   'trading_signals', 'support_resistance', 'ma_crossovers',
                   'monthly_returns_heatmap', 'correlations', 'sector_performance']:
            try:
                dataframes[key] = pd.DataFrame(all_data[key])
                logger.info(f"✅ {key} DataFrame created: {len(dataframes[key])} rows")
            except Exception as e:
                logger.error(f"❌ Error creating {key} DataFrame: {e}")
                dataframes[key] = pd.DataFrame()

        insertions = [
            ('stock_info', self.inserter.insert_stock_info, all_data['stock_info'], None),
            ('daily_prices', self.inserter.insert_daily_prices, dataframes['historical'], None),
            ('quotes', 'fact_realtime_quotes', dataframes['quotes'], ''),
            ('fundamentals', 'fact_fundamentals', dataframes['fundamentals'], ''),
            ('income_statements', 'fact_income_statement', dataframes['income_statements'], 'ON CONFLICT (symbol, fiscal_date, period) DO NOTHING'),
            ('balance_sheets', 'fact_balance_sheet', dataframes['balance_sheets'], 'ON CONFLICT (symbol, fiscal_date, period) DO NOTHING'),
            ('cashflows', 'fact_cash_flow', dataframes['cashflows'], 'ON CONFLICT (symbol, fiscal_date, period) DO NOTHING'),
            ('returns', 'fact_returns', dataframes['returns'], 'ON CONFLICT (symbol, calculation_date) DO NOTHING'),
            ('weekly', 'fact_weekly_prices', dataframes['weekly'], 'ON CONFLICT (symbol, week_start_date) DO NOTHING'),
            ('monthly', 'fact_monthly_prices', dataframes['monthly'], 'ON CONFLICT (symbol, month_date) DO NOTHING'),
            ('yearly', 'fact_yearly_summary', dataframes['yearly'], 'ON CONFLICT (symbol, year) DO NOTHING'),
            ('dividends', 'fact_dividend_history', dataframes['dividends'], 'ON CONFLICT (symbol, ex_date) DO NOTHING'),
            ('splits', 'fact_stock_splits', dataframes['splits'], 'ON CONFLICT (symbol, split_date) DO NOTHING'),
            ('trading_signals', 'fact_trading_signals', dataframes['trading_signals'], ''),
            ('support_resistance', 'fact_support_resistance', dataframes['support_resistance'], ''),
            ('ma_crossovers', 'fact_ma_crossovers', dataframes['ma_crossovers'], ''),
            ('monthly_returns_heatmap', 'fact_monthly_returns_heatmap', dataframes['monthly_returns_heatmap'], 'ON CONFLICT (symbol, year, month) DO NOTHING'),
            ('correlations', 'fact_correlations', dataframes['correlations'], 'ON CONFLICT (symbol_1, symbol_2, calculation_date) DO NOTHING'),
            ('sector_performance', 'fact_sector_performance', dataframes['sector_performance'], 'ON CONFLICT (sector, calculation_date) DO NOTHING')
        ]

        for item in insertions:
            key, table_or_func, data, conflict = item

            # Check if it's a custom insert function or generic table
            if callable(table_or_func):
                # Custom insert function (stock_info, daily_prices)
                if isinstance(data, list) and len(data) > 0:
                    logger.info(f"💾 Inserting {key}... ({len(data)} records)")
                    count = table_or_func(data)
                    self.insertion_results[key] = {'attempted': len(data), 'inserted': count}
                    logger.info(f"   ✅ {count:,} records inserted")
                elif isinstance(data, pd.DataFrame) and not data.empty:
                    logger.info(f"💾 Inserting {key}... ({len(data)} records)")
                    count = table_or_func(data)
                    self.insertion_results[key] = {'attempted': len(data), 'inserted': count}
                    logger.info(f"   ✅ {count:,} records inserted")
                else:
                    logger.warning(f"   ⚠️ {key}: No data to insert (type: {type(data)}, empty: {len(data) if hasattr(data, '__len__') else 'N/A'})")
                    self.insertion_results[key] = {'attempted': 0, 'inserted': 0}
            else:
                # Generic table insert
                table_name = table_or_func
                if isinstance(data, pd.DataFrame) and not data.empty:
                    logger.info(f"💾 Inserting {table_name}... ({len(data)} records)")
                    count = self.inserter.insert_generic_table(table_name, data, conflict)
                    self.insertion_results[key] = {'attempted': len(data), 'inserted': count}
                    logger.info(f"   ✅ {count:,} records inserted")
                else:
                    logger.warning(f"   ⚠️ {table_name}: No data to insert (DataFrame empty: {data.empty if isinstance(data, pd.DataFrame) else 'Not a DF'})")
                    self.insertion_results[key] = {'attempted': 0, 'inserted': 0}

    def verify_all_data(self):
        """Verify data in all tables"""
        logger.info("\n🔍 VERIFYING DATA IN DATABASE...")
        logger.info("=" * 80)

        tables_to_verify = [
            ('dim_stocks', 'Stock Information'),
            ('fact_realtime_quotes', 'Real-time Quotes'),
            ('fact_daily_prices', 'Daily Prices'),
            ('fact_fundamentals', 'Fundamentals'),
            ('fact_income_statement', 'Income Statements'),
            ('fact_balance_sheet', 'Balance Sheets'),
            ('fact_cash_flow', 'Cash Flows'),
            ('fact_returns', 'Returns'),
            ('fact_weekly_prices', 'Weekly Prices'),
            ('fact_monthly_prices', 'Monthly Prices'),
            ('fact_yearly_summary', 'Yearly Summary'),
            ('fact_dividend_history', 'Dividends'),
            ('fact_stock_splits', 'Stock Splits'),
            ('fact_trading_signals', 'Trading Signals'),
            ('fact_support_resistance', 'Support/Resistance'),
            ('fact_ma_crossovers', 'MA Crossovers'),
            ('fact_monthly_returns_heatmap', 'Monthly Returns Heatmap'),
            ('fact_correlations', 'Correlations'),
            ('fact_sector_performance', 'Sector Performance')
        ]

        verification_results = {}
        total_records = 0
        tables_with_data = 0

        for table_name, display_name in tables_to_verify:
            count = self.db.verify_table_data(table_name)
            verification_results[table_name] = count
            total_records += count

            if count > 0:
                tables_with_data += 1
                status = "✅"
            else:
                status = "⚠️"

            logger.info(f"{status} {display_name:<30}: {count:>10,} records")

        logger.info("=" * 80)
        logger.info(f"📊 TOTAL RECORDS IN DATABASE: {total_records:,}")
        logger.info(f"✅ TABLES WITH DATA: {tables_with_data}/{len(tables_to_verify)}")
        logger.info("=" * 80)

        # Final status message
        missing_tables = [name for name, count in verification_results.items() if count == 0]

        if not missing_tables:
            logger.info("\n" + "🎉" * 40)
            logger.info("✅ ✅ ✅  ALL TABLES INSERTED SUCCESSFULLY!  ✅ ✅ ✅")
            logger.info("🎉" * 40)
            logger.info(f"\n📊 Summary:")
            logger.info(f"   • {len(tables_to_verify)} tables populated")
            logger.info(f"   • {total_records:,} total records")
            logger.info(f"   • 100% success rate")
            logger.info(f"\n✨ Your database is ready for Power BI!")
        else:
            logger.warning("\n⚠️ WARNING: The following tables have NO data:")
            for table in missing_tables:
                logger.warning(f"   - {table}")
            logger.warning("\nThis might indicate:")
            logger.warning("   1. Data collection issues")
            logger.warning("   2. API errors")
            logger.warning("   3. Data processing problems")

            if tables_with_data > 0:
                success_rate = (tables_with_data / len(tables_to_verify)) * 100
                logger.info(f"\n✅ Partial Success: {tables_with_data}/{len(tables_to_verify)} tables ({success_rate:.1f}%) have data")

        return verification_results

    def print_summary(self, all_data):
        logger.info("\n" + "=" * 80)
        logger.info("📊 DATA COLLECTION SUMMARY")
        logger.info("=" * 80)

        summary_items = [
            ('Stocks Processed', len(all_data['stock_info'])),
            ('Daily Price Records', sum(len(df) for df in all_data['historical'])),
            ('Fundamentals', len(all_data['fundamentals'])),
            ('Income Statements', len(all_data['income_statements'])),
            ('Balance Sheets', len(all_data['balance_sheets'])),
            ('Cash Flows', len(all_data['cashflows'])),
            ('Dividends', len(all_data['dividends'])),
            ('Stock Splits', len(all_data['splits'])),
            ('Trading Signals', len(all_data['trading_signals'])),
            ('MA Crossovers', len(all_data['ma_crossovers'])),
            ('Monthly Returns (Heatmap)', len(all_data['monthly_returns_heatmap'])),
            ('Correlations', len(all_data['correlations'])),
            ('Sector Metrics', len(all_data['sector_performance']))
        ]

        for item, count in summary_items:
            logger.info(f"{item:<30}: {count:>10,}")

        logger.info("=" * 80)

        # Print insertion results
        if self.insertion_results:
            logger.info("\n📥 INSERTION RESULTS")
            logger.info("=" * 80)
            for key, result in self.insertion_results.items():
                attempted = result['attempted']
                inserted = result['inserted']
                success_rate = (inserted / attempted * 100) if attempted > 0 else 0
                status = "✅" if inserted == attempted else "⚠️" if inserted > 0 else "❌"
                logger.info(f"{status} {key:<30}: {inserted:>6,} / {attempted:>6,} ({success_rate:>5.1f}%)")
            logger.info("=" * 80)

    def print_final_summary(self, verification_results):
        """Print a beautiful final summary box"""
        total_records = sum(verification_results.values())
        tables_with_data = sum(1 for count in verification_results.values() if count > 0)
        total_tables = len(verification_results)

        print("\n\n")
        print("╔" + "═"*78 + "╗")
        print("║" + " "*25 + "🎯 FINAL SUMMARY" + " "*37 + "║")
        print("╠" + "═"*78 + "╣")
        print(f"║  📊 Total Records Inserted:  {total_records:>10,}" + " "*35 + "║")
        print(f"║  ✅ Tables Populated:         {tables_with_data:>2}/{total_tables}" + " "*43 + "║")
        print(f"║  📈 Success Rate:             {(tables_with_data/total_tables*100):>5.1f}%" + " "*39 + "║")
        print("╠" + "═"*78 + "╣")

        # Show top 5 tables by record count
        sorted_tables = sorted(verification_results.items(), key=lambda x: x[1], reverse=True)[:5]
        print("║  🏆 Top 5 Tables:" + " "*58 + "║")
        for i, (table, count) in enumerate(sorted_tables, 1):
            table_display = table.replace('fact_', '').replace('dim_', '').replace('_', ' ').title()[:30]
            print(f"║     {i}. {table_display:<32} {count:>10,} records" + " "*(78-51-len(str(count))) + "║")

        print("╠" + "═"*78 + "╣")

        if tables_with_data == total_tables:
            print("║  " + "🎉"*37 + "  ║")
            print("║  " + " "*15 + "✅ ALL TABLES SUCCESSFULLY POPULATED! ✅" + " "*16 + "  ║")
            print("║  " + "🎉"*37 + "  ║")
        else:
            missing_count = total_tables - tables_with_data
            print(f"║  ⚠️  {missing_count} table(s) have no data - check logs above for details" + " "*(78-58-len(str(missing_count))) + "║")

        print("╚" + "═"*78 + "╝")
        print("\n")

# ============================================
# UTILITIES
# ============================================

def test_database_connection():
    logger.info("🔌 Testing database connection...")

    if not Config.validate_db_config():
        logger.error("❌ Please update DB_CONFIG in the Config class!")
        return False

    db = DatabaseManager(Config.DB_CONFIG)
    if db.connect():
        logger.info("✅ Database connection successful!")

        # Test a simple query
        result = db.fetch_query("SELECT version()")
        if result:
            logger.info(f"📊 PostgreSQL version: {result[0][0]}")

        db.disconnect()
        return True
    else:
        logger.error("❌ Database connection failed!")
        return False

def quick_start_guide():
    guide = """
    ╔══════════════════════════════════════════════════════════════════════════╗
    ║           🚀 GOOGLE COLAB STOCK PIPELINE - READY TO RUN!               ║
    ╚══════════════════════════════════════════════════════════════════════════╝

    ✅ DATABASE CONFIGURED: Neon PostgreSQL
    📊 STOCKS: 26 companies across 7 sectors
    📅 DATA RANGE: 10 years historical
    ⏱️  ESTIMATED TIME: 15-20 minutes

    🎯 QUICK START:
    ─────────────────────────────────────────────────────────────────────────
    1. Run: test_database_connection()  # Optional - test first
    2. Run: main()                      # Execute full pipeline

    ╚══════════════════════════════════════════════════════════════════════════╝
    """
    print(guide)

# ============================================
# MAIN EXECUTION
# ============================================

def main():
    """Main execution function"""
    start_time = datetime.now()

    print("\n" + "="*80)
    print("🚀 STARTING STOCK MARKET DATA PIPELINE")
    print("="*80)
    print(f"⏰ Start Time: {start_time.strftime('%Y-%m-%d %H:%M:%S')}")
    print("="*80 + "\n")

    pipeline = StockPipeline(Config)
    success = pipeline.run()

    end_time = datetime.now()
    duration = end_time - start_time

    print("\n" + "="*80)
    print("⏱️  EXECUTION SUMMARY")
    print("="*80)
    print(f"Start Time:    {start_time.strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"End Time:      {end_time.strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"Duration:      {duration}")
    print("="*80)

    if success:
        print("\n" + "🎉"*40)
        print("✅ ✅ ✅  PIPELINE COMPLETED SUCCESSFULLY!  ✅ ✅ ✅")
        print("🎉"*40)
        print("\n✨ Database is ready! Connect to Power BI to visualize your data.")
        print("\n" + "="*80)
    else:
        print("\n" + "❌"*40)
        print("❌ ❌ ❌  PIPELINE FAILED!  ❌ ❌ ❌")
        print("❌"*40)
        print("\n⚠️  Check the logs above for error details")
        print("\n" + "="*80)

    return success

# ============================================
# RUN
# ============================================

if __name__ == "__main__":
    quick_start_guide()

    # Uncomment to test connection first:
    # test_database_connection()

    # Run the pipeline
    main()
